name: Dev deployment

on:
  push:
    branches: ['dev']
  workflow_dispatch:

jobs:
  ci:
    uses: ./.github/workflows/ci.yml
    secrets: inherit

  deploy:
    needs: ci
    uses: ./.github/workflows/deploy.yml
    with:
      runner_label: dev
      environment_name: dev
    secrets: inherit
